config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :bills
  end
  devise_for :admins, skip: [:registrations]
  devise_for :users

  authenticated :admin do
    root to: "admin/bills#index", as: :admin_root
  end


  post 'bill_pay/:id', to:"homes#pay", as: :pay_bill 

  

  root "homes#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  has_many :bills
end

app/models/admin/bill.rb
class Admin::Bill < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :admin_bills, class_name: 'Admin::Bill'
end

app/controllers/admin/bills_controller.rb
class Admin::BillsController < ApplicationController
  before_action :set_admin_bill, only: %i[ show edit update destroy ]
  before_action :authenticate_admin!

  def index
    @admin_bills = Admin::Bill.all
  end



  def new
    @admin_bill = Admin::Bill.new
  end

  def edit
  end

  def create
    @admin_bill = Admin::Bill.new(admin_bill_params)

    respond_to do |format|
      if @admin_bill.save
        format.html { redirect_to admin_bills_url, notice: "Bill was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @admin_bill.update(admin_bill_params)
        format.html { redirect_to admin_bills_url, notice: "Bill was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @admin_bill.destroy

    respond_to do |format|
      format.html { redirect_to admin_bills_url, notice: "Bill was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_bill
      @admin_bill = Admin::Bill.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def admin_bill_params
      params.require(:admin_bill).permit(:user_id, :bill_date, :amount, :paid)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  before_action :authenticate_user!

  def index
    @bills = current_user&.admin_bills
  end

  def pay
    @bill = Admin::Bill.find(params[:id])
    @bill.update(paid: true)
    redirect_to root_path
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/bills/_bill.html.erb
<table class="table table-striped">
  <tbody>
      <tr class="<%= 'table-success' if bill.paid? %>">
        <td>
          <div id="<%= dom_id bill %>">
            <p>
              <strong>User:</strong>
              <%= bill.user.email %>
            </p>

            <p>
              <strong>Bill date:</strong>
              <%= bill.bill_date %>
            </p>

            <p>
              <strong>Amount:</strong>
              <%= bill.amount %>
            </p>

            <p>
              <strong>Paid:</strong>
              <%= bill.paid %>
            </p>

            <%= link_to "Edit bill", edit_admin_bill_path(bill), class: 'btn btn-warning btn-sm mr-1' %>
            <%= button_to "Delete Bill", bill, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
          </div>
        </td>
      </tr>
  </tbody>
</table>

app/views/admin/bills/_form.html.erb
<%= form_with(model: admin_bill) do |form| %>
  <% if admin_bill.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(admin_bill.errors.count, "error") %> prohibited this admin_bill from being saved:</h2>

      <ul>
        <% admin_bill.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.collection_select :user_id, User.order(:email), :id, :email %>
  </div>

  <div>
    <%= form.label :bill_date, style: "display: block" %>
    <%= form.date_field :bill_date %>
  </div>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.text_field :amount %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/bills/edit.html.erb
<h1>Editing bill</h1>

<%= render "form", admin_bill: @admin_bill %>

<br>

<div>
  <%= link_to "Show this bill", @admin_bill %> |
  <%= link_to "Back to bills", admin_bills_path %>
</div>

app/views/admin/bills/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="d-flex justify-content-between align-items-center">
  <%= link_to "Generate bill", new_admin_bill_path, class:"btn btn-primary mt-5" %>
  <%= button_to "Sign Out", destroy_admin_session_path, method: :delete, class:"btn btn-danger mt-5" %>
</div>
<h1 class="mt-5">Bills</h1>

<div id="admin_bills">
  <% @admin_bills.each do |admin_bill| %>
    <%= render admin_bill %>
  <% end %>
</div>

app/views/admin/bills/new.html.erb
<h1>New bill</h1>

<%= render "form", admin_bill: @admin_bill %>

<br>

<div>
  <%= link_to "Back to bills", admin_bills_path %>
</div>

app/views/homes/index.html.erb
<div class="d-flex justify-content-end align-items-center">
  <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class:"btn btn-danger mt-5" %>
</div>
<h1 class="text-center">Your Bills!</h1>
<table class="container table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Bill Date</th>
      <th>Amount</th>
      <th>Paid</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @bills.each do |bill| %>
      <tr>
        <td><%= bill.id %></td>
        <td><%= bill.bill_date %></td>
        <td><%= bill.amount %></td>
        <td><%= bill.paid %></td>
        
        <td>
          <% if !bill.paid? %>
            <%= button_to "Click To Pay", pay_bill_path(bill), method: :post, class: 'btn btn-primary' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Electricity</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="container">
    <%= yield %>
  </body>
</html>